spring:
  application:
    name: demo
  datasource:
    url: <<url>>
    username: <<username>>
    password: <<passwords>>
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
